//===- ToyCombine.cpp - Canonicalization patterns for Toy -----------------===//
//
// Adapted from mlir/examples/toy/Ch7/mlir/ToyCombine.cpp in the LLVM Project,
// under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// The rewrites that need Toy's own semantics, and are therefore impossible once
// the program is loop nests over memrefs: transpose(transpose(x)) is only
// recognisable while the operation still says "transpose".
//
// Two ways of writing a pattern meet here. The three reshape rules come from
// ToyCombine.td through mlir-tblgen (declarative, see ToyCombine.inc); the
// transpose rule is C++ because it has to look through an operand at the
// operation that defined it, which DRR's tree matching cannot express.
//
// Nothing in this file runs a pass. Patterns are registered on the operations
// themselves and the generic canonicalizer picks them up, which is how a
// dialect contributes to a pass that has never heard of it. The folders that
// upstream also keeps in this file live in dialect/Folders.cpp here, since
// folding is part of an operation's definition rather than a rewrite.
//
//===----------------------------------------------------------------------===//

#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Value.h"
#include "toy/Dialect.h"

#include "llvm/Support/Casting.h"

#include <cstddef>

using namespace mlir;
using namespace toy;

namespace {
/// The patterns generated from ToyCombine.td: ReshapeReshapeOptPattern,
/// RedundantReshapeOptPattern and FoldConstantReshapeOptPattern.
#include "ToyCombine.inc"
} // namespace

/// transpose(transpose(x)) -> x
///
/// The pattern matches the outer transpose and asks what defined its operand;
/// if that is another transpose, the pair cancels and the original input
/// replaces the result. Both transposes are then dead, and `Pure` on
/// TransposeOp is what permits the driver to delete them. Without it MLIR
/// must assume a side effect and keeps them.
struct SimplifyRedundantTranspose : public mlir::OpRewritePattern<TransposeOp> {
  /// The benefit orders this against competing patterns; with one pattern per
  /// op here it only matters for reproducibility of the application order.
  SimplifyRedundantTranspose(mlir::MLIRContext *context)
      : OpRewritePattern<TransposeOp>(context, /*benefit=*/1) {}

  llvm::LogicalResult
  matchAndRewrite(TransposeOp op,
                  mlir::PatternRewriter &rewriter) const override {
    mlir::Value transposeInput = op.getOperand();
    TransposeOp transposeInputOp = transposeInput.getDefiningOp<TransposeOp>();

    // The operand came from somewhere else (a block argument, a constant, any
    // other op): nothing to cancel.
    if (!transposeInputOp)
      return failure();

    // Every mutation goes through the rewriter so the driver can track what
    // changed and re-examine the affected operations.
    rewriter.replaceOp(op, {transposeInputOp.getOperand()});
    return success();
  }
};

/// Registration hook generated by `hasCanonicalizer = 1` on TransposeOp.
void TransposeOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                              MLIRContext *context) {
  results.add<SimplifyRedundantTranspose>(context);
}

/// Registration hook generated by `hasCanonicalizer = 1` on ReshapeOp.
void ReshapeOp::getCanonicalizationPatterns(RewritePatternSet &results,
                                            MLIRContext *context) {
  results.add<ReshapeReshapeOptPattern, RedundantReshapeOptPattern,
              FoldConstantReshapeOptPattern>(context);
}
